// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_k5YwAGEI_c0rkLdXzPmdHHSSNGEE3yA',
    appId: '1:454730873487:web:bba1143c8d8cc1e0ed8efa',
    messagingSenderId: '454730873487',
    projectId: 'notes-management-system-a0a74',
    authDomain: 'notes-management-system-a0a74.firebaseapp.com',
    storageBucket: 'notes-management-system-a0a74.firebasestorage.app',
    measurementId: 'G-ZGNZLQJBDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCsTIIlnLUz1MUyAOL741ypgj7K-_IxxU',
    appId: '1:454730873487:android:4db30083ffa5b577ed8efa',
    messagingSenderId: '454730873487',
    projectId: 'notes-management-system-a0a74',
    storageBucket: 'notes-management-system-a0a74.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_k5YwAGEI_c0rkLdXzPmdHHSSNGEE3yA',
    appId: '1:454730873487:web:369c88265c1bc020ed8efa',
    messagingSenderId: '454730873487',
    projectId: 'notes-management-system-a0a74',
    authDomain: 'notes-management-system-a0a74.firebaseapp.com',
    storageBucket: 'notes-management-system-a0a74.firebasestorage.app',
    measurementId: 'G-4VSRCT00R7',
  );
}
